### ISSUE TITLE
migrate to Grails3

### ISSUE THREAD

**Issue by puneetbehl** [kefirfromperm/grails-asynchronous-mail#41]

**Comment by puneetbehl** [comment]
I've migrated this plugin to Grails-3.0.1, please let me know how we can proceed. Here is the github link for migrated version of plugin. https://github.com/puneetbehl/grails3-asynchronous-mail

**Comment by kefirfromperm** [comment]
Please, make a pull request and I publish it.

**Comment by kefirfromperm** [comment]
Do you use my codebase?

**Comment by stokito** [comment]
As I see, @puneetbehl created new project in Grails 3 and copied some code from this version.
It is not good because we lost all commits history that may be useful.

**Comment by puneetbehl** [comment]
Yes @kefirfromperm  I've used your codebase and created a new grails plugin by following instructions on http://grails.github.io/grails-doc/latest/guide/upgrading.html#upgradingPlugins 

Please let me know how we can integrate with this, one way I could think of is:
 - Create a new branch named grails-2.3.x of the master.
 - Push this branch to remote.
 - Now checkout to master and create a directory named "older-version".
 - Move all existing codebase into this directory.
 - Now, pull the changes from this new grails plugin to master.

Waiting to hear from you.

**Comment by puneetbehl** [comment]
@kefirfromperm I've updated the plugin so that we do-not lose commit history and rewritten the test cases to Spock. Also, I am thinking that we should upload the plugin to bintary. Here is url for updated plugin https://github.com/puneetbehl/grails-asynchronous-mail

**Comment by puneetbehl** [comment]
Hi Vitalii Samolovskikh
Any updates? I'd already made a pull request. Please do reply of any issues or concerns.
RegardsPuneet Behl 


     On Thursday, 16 April 2015 2:23 PM, Vitalii Samolovskikh <notifications@github.com> wrote:
   

 Please, make a pull request and I publish it.—

**Comment by kefirfromperm** [comment]
I haven't enough time now. I'll merge it as soon as possible.
