### ISSUE TITLE
Setting for disabling attachment storing

### ISSUE THREAD

**Issue by pgdoval** [kefirfromperm/grails-asynchronous-mail#56]
I want to keep in my DB all the information except the attachments, because they make my DB grow very fast, so having a setting similar to delete:true but only referring to attachments would be great.
I can only see 2 options:
- adding a new value for the delete property, so it can hold true, false and attachments
- adding a new property, deleteAttachments, which will be false by default

**Comment by kefirfromperm** [comment]
It will be better the configuration property have the same options - false, true, attachments.

**Comment by kefirfromperm** [comment]
Resolved 2.0.0.RC3
