### ISSUE TITLE
Move full documentation to README.md

### ISSUE THREAD

**Issue by kefirfromperm** [kefirfromperm/grails-asynchronous-mail#57]
The full plugin documentation is on [the old plugin page](http://grails.org/plugin/asynchronous-mail). It's needed to move it to README.md file and actualize.

**Comment by puneetbehl** [comment]
@kefirfromperm What are your thoughts about creating separate docs in addition to moving in README.md ?

**Comment by kefirfromperm** [comment]
@puneetbehl 
I think there is not so much documentation for creating a separate one. Maybe I'll do it when have more free time. Now I want to move the documentation from the old plugin page to README.md because [the new plugin page](https://grails.org/plugins.html#plugin/asynchronous-mail) takes it from the README.md

**Comment by puneetbehl** [comment]
Yes, I agree that makes perfect sense to update `README.md` and for separate docs, I can work on it.

**Comment by kefirfromperm** [comment]
So it would be great!

**Comment by kefirfromperm** [comment]
Because my English is... You known :)
