### ISSUE TITLE
Can store the mail encrypted?

### ISSUE THREAD

**Issue by vaibhavgarg90** [kefirfromperm/grails-asynchronous-mail#61]
Well not really a bug, more of a feature suggest. Is it possible to store the mail encrypted in DB? The project I am working on currently, has some private information and it would be ideal to store the mail content in encrypted format. Is it possible currently?

**Comment by kefirfromperm** [comment]
Currently it is not possible. Sorry.
What do you want to encrypt? The message subject and body or attachments too?

**Comment by kefirfromperm** [comment]
Try to use encryption on DB level.

**Comment by gargvaibhav90** [comment]
At least attachments have to be encrypted if not the complete mail.

**Comment by kefirfromperm** [comment]
Won't fix.
