### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by maxiagrace** [kefirfromperm/grails-asynchronous-mail#62]
D:\Dev\Java\jdk1.7.0_79\bin\java ...
|Running application...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> grails/plugin/asyncmail/AsynchronousMailService : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error |
Failed to start server (Use --stacktrace to see the full trace)

Process finished with exit code 1

**Comment by maxiagrace** [comment]
Have try RC2, RC1, both have this problem in grails 3 with JDK 1.7

**Comment by kefirfromperm** [comment]
Resolved in RC3
https://github.com/kefirfromperm/grails-asynchronous-mail/commit/3a2a3d4feed587229d4b3f53fb3fbe25ab54e9fa
