### ISSUE TITLE
How to load email body from a view (.gsp) file like another plugin of mail ?

### ISSUE THREAD

**Issue by wureka** [kefirfromperm/grails-asynchronous-mail#65]
Can I load email body from a view file just like that of https://grails.org/plugins.html#plugin/mail ?

You may refer to line 277 in https://github.com/gpc/grails-mail/blob/master/src/groovy/grails/plugin/mail/MailMessageBuilder.groovy

Many thanks

**Comment by kefirfromperm** [comment]
Yes, asynchronous mail plugin supports all features of mail plugin.
