### ISSUE TITLE
Add support of List-Unsubscribe

### ISSUE THREAD

**Issue by demon101** [kefirfromperm/grails-asynchronous-mail#75]
Is it possible to add support of List-Unsubscribe mail header?

https://www.ietf.org/rfc/rfc2369.txt

I see, but, as I understand, it exists for attachments
```
/** Additional headers */
    Map<String, String> headers
```

**Comment by kefirfromperm** [comment]
The headers not only for attachments. I just use the headers in the mail plugin and don't see any reasons to to do a different field. Use headers.
