### ISSUE TITLE
onStartup() not called 

### ISSUE THREAD

**Issue by MLoenhardt** [kefirfromperm/grails-asynchronous-mail#80]
Fresh grails 3.2.12 project with plugin 2.0.1-3.2.x added to dependencies.
onStartup() not called, perhaps because of missing params.
Should overwrite void onStartup(Map<String, Object> event)
[myapp_3_2_12_asyncmail.zip](https://github.com/kefirfromperm/grails-asynchronous-mail/files/1742179/myapp_3_2_12_asyncmail.zip)

**Comment by kefirfromperm** [comment]
Fixed in 2.0.2, 2.0.2-3.2.x
